---
version: '3'
services:
  cloudflare:
    container_name: cloudflareDDNS
    image: oznu/cloudflare-ddns:latest
    networks:
      - devrack
    env_file:
      - ../server.env
      - ./cloudflare.env
    environment:
      PUID: 99
      PGID: 100
      TZ: 'America/Chicago'
      HOST_OS: Unraid
      HOST_HOSTNAME: ${SERVER_NAME}
      HOST_CONTAINERNAME: cloudflareDDNS
      #EMAIL: ${CLOUDFLARE_EMAIL}
      API_KEY: ${CLOUDFLARE_API_KEY}
      ZONE: ${CLOUDFLARE_DOMAIN}
      SUBDOMAIN: ${CLOUDFLARE_SUBDOMAIN}
      PROXIED: true
      RRTYPE: A #IPv6 is AAAA
    labels:
      - 'net.unraid.docker.icon=https://i.imgur.com/PKa3Sm2. -l net.unraid.docker.managed=dockermanpng'
    restart: always

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
