---
version: '3'
services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    networks:
      fixed_ip:
        ipv4_address: ${ADGUARD_IP}  # Set static IP address
    ports:
      - "${SERVER_IP}:53:53/tcp"
      - "${SERVER_IP}:53:53/udp"
      - "${SERVER_IP}:784:784/udp"
      - "${SERVER_IP}:853:853/tcp"
      - "${SERVER_IP}:3000:3000/tcp"
      - "${SERVER_IP}:80-443:80/tcp"
    volumes:
      - /mnt/user/appdata/adguard/workingdir:/opt/adguardhome/work
      - /mnt/user/appdata/adguard/config:/opt/adguardhome/conf
    restart: always

  cloudflare:
    container_name: cloudflareDDNS
    image: oznu/cloudflare-ddns:latest
    networks:
      - proxy
    environment:
      EMAIL: ${CLOUDFLARE_EMAIL}
      API_KEY: ${CLOUDFLARE_API_KEY}
      ZONE: ${CLOUDFLARE_DOMAIN}
      SUBDOMAIN: ${CLOUDFLARE_SUBDOMAIN}
      PROXIED: true
      RRTYPE: A #IPv6 is AAAA
    restart: always

  nginx:
    container_name: nginxproxymanager
    image: jlesage/nginx-proxy-manager:latest
    networks:
      - proxy
    ports:
      - "${SERVER_IP}:8080:8080" # HTTP Port
      - "${SERVER_IP}:8181:8181" # Admin Web Port
      - "${SERVER_IP}:4443:4443" # HTTPS Port
    volumes:
      - /mnt/user/appdata/core/nginxproxymanager:/config:rw
    environment:
      APP_NICENESS: 0 # A niceness value of -20 is the highest priority and 19 is the lowest priority. NOTE: Setting a negative value requires additional permissions.
      DISABLE_IPV6: 1 # disabled
    restart: always

networks:
  fixed_ip:
    driver: bridge
    external:
      name: ${UNRAID_BRIDGE_NAME}  # Specify the name of the existing bridge network in Unraid
  proxy:
    name: ${DOCKER_NETWORK}
    driver: bridge
    external: true
