---
version: '3'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      fixed_pi:
        ipv4_address: ${PIHOLE_IP}
    ports:
      - :53:53
      - :67:67 # Only required if you are using Pi-hole as your DHCP server
      - :80:80
    volumes:
      - /mnt/user/appdata/pihole/pihole/:/etc/pihole
      - /mnt/user/appdata/pihole/pihole/dnsmasq.d:/etc/dnsmasq.d   
    environment:
      TZ: 'America/Chicago' # US
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      DNS1: 1.1.1.1 # Cloudflare
      DNS2: 8.8.8.8 # Google
      INTERFACE: ${HARDWARE_CONNECTION}
      ServerIP: ${PIHOLE_IP}
      IPv6: False
      DNSMASQ_LISTENING: all
      PIHOLE_DNS_: '1.1.1.1;8.8.8.8'
      WEBUIBOXEDLAYOUT: boxed 
    restart: unless-stopped
    
#  <SERVICE_NAME>:
#    container_name: <CONTAINER>
#    image: <CONTAINER_REPO>:<TAG>
#    networks:
#      - proxy
#    ports:
#      - ${SERVER_NAME}:<PORTS>:<PORTS>
#    volumes:
#      - /mnt/user/appdata/<SERVICE_NAME>/<CONTAINER>/:/
#    environment:
#    restart: unless-stopped
   
networks:
#  static:
#    name: ${HARDWARE_CONNECTION}
#    driver: bridge
#    enable_ipv6: false
#    ipam:
#      driver: default
#      config:
#        - subnet: '192.168.1.0/24'
#          gateway: ${PIHOLE_IP}
  fixed_pi:
    name: ${HARDWARE_CONNECTION}
  proxy:
    name: ${DOCKER_NETWORK}
    driver: bridge
    external: true
    