services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    networks:
      - devrack
    volumes:
      - /mnt/user/appdata/tools/backrest/data:/data
      - /mnt/user/appdata/tools/backrest/config:/config
      - /mnt/user/appdata/tools/backrest/cache:/cache
      - /mnt/user/cloud:/userdata/cloud # (Unraid) shares location
      - /mnt/user/restic-repos:/repos # [optional] mount repos if using local storage, not necessary for remotes e.g. B2, S3, etc.
    environment:
      - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
      - TZ=${TZ} # set the timezone for the container, used as the timezone for cron jobs.
    restart: unless-stopped
    ports:
      - ${SERVER_IP}:9898:9898

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
