---
version: '3'
services:
  db_cache:
    container_name: redis_authentik
    image: bitnami/redis:latest
    networks:
      - proxy
    ports:
      - ${SERVER_NAME}:6379:6379
    volumes:
      - /mnt/user/appdata/redis_authentik/bitnami:/bitnami
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped

  db_sql:
    container_name: postgres_authentik
    image: postgres:12.5-alpine
    networks:
      - proxy
    ports:
      - ${SERVER_NAME}:5432:5432
    volumes:
      - /mnt/user/appdata/postgres_authentik/data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    
  authentik_worker:
    container_name: authentik-worker
    image: beryju/authentik:latest
    networks:
      - proxy
    ports:
    volumes:
      - /mnt/user/appdata/authentik/backups:/backups
      - /mnt/user/appdata/authentik/media:/media
      - /mnt/user/appdata/authentik/certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/user/appdata/authentik/templates:/templates
      - /mnt/user/appdata/authentik/geoip:/geoip
    environment:
      - AUTHENTIK_REDIS__HOST=${REDIS_CONTRAINER_NAME}
      - AUTHENTIK_REDIS__PASSWORD=${REDIS_PASSWORD}
      - AUTHENTIK_POSTGRESQL__HOST=${POSTGRES_CONTAINER_NAME}
      - AUTHENTIK_POSTGRESQL__USER=${POSTGRES_USER}
      - AUTHENTIK_POSTGRESQL__NAME=${POSTGRES_DB}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${POSTGRES_PASSWORD}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=true
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_KEY}
    restart: unless-stopped
    
  authentik:
    container_name: authentik
    privileged: true
    image: beryju/authentik:latest
    networks:
      - proxy
    ports: 
      - ${SERVER_NAME}:9000:9000
      - ${SERVER_NAME}:9443:9443
    volumes:
      - /mnt/user/appdata/authentik/templates/:/templates
      - /mnt/user/appdata/authentik/geoip:/geoip
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/user/appdata/authentik/media/:/media
    environment:
      - AUTHENTIK_REDIS__HOST=${REDIS_CONTRAINER_NAME}
      - AUTHENTIK_POSTGRESQL__HOST=${POSTGRES_CONTAINER_NAME}
      - AUTHENTIK_POSTGRESQL__USER=${POSTGRES_USER}
      - AUTHENTIK_POSTGRESQL__NAME=${POSTGRES_DB}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${POSTGRES_PASSWORD}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=true
      - GEOIPUPDATE_ACCOUNT_ID=null
      - GEOIPUPDATE_LICENSE_KEY=null
      - AUTHENTIK_AUTHENTIK__GEOIP=/geoip/GeoLite2-City.mmdb
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_KEY}
      - AUTHENTIK_REDIS__PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped

networks:
  proxy:
    name: ${DOCKER_NETWORK}
    driver: bridge
    external: true
    