---
version: '3'
services:
  postgresql:
    container_name: postgres
    image: postgres:12-alpine
    networks:
      - proxy
    ports:
      - ${SERVER_NAME}:5432:5432
    volumes:
      - /mnt/user/appdata/postgres/data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER:-authentik}
      - POSTGRES_DB=${POSTGRES_DB:-authentik}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - proxy
    ports:
      - ${SERVER_NAME}:6379:6379
    volumes:
      - /mnt/user/appdata/redis:/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    restart: unless-stopped
  
  server:
    container_name: authentik
    image: beryju/authentik:latest
    command: server
    networks:
      - proxy
    ports: 
      - ${SERVER_NAME}:9000:9000
      - ${SERVER_NAME}:9443:9443
    volumes:
      - /mnt/user/appdata/authentik/templates/:/templates
      - /mnt/user/appdata/authentik/geoip:/geoip
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/user/appdata/authentik/media/:/media
    environment:
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_POSTGRESQL__HOST=postgres
      - AUTHENTIK_POSTGRESQL__USER=${POSTGRES_USER:-authentik}
      - AUTHENTIK_POSTGRESQL__NAME=${POSTGRES_DB:-authentik}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${POSTGRES_PASSWORD}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=true
#      - GEOIPUPDATE_ACCOUNT_ID=null
#      - GEOIPUPDATE_LICENSE_KEY=null
#      - AUTHENTIK_AUTHENTIK__GEOIP=/geoip/GeoLite2-City.mmdb
      - AUTHENTIK_SECRET_KEY=${secret_key}
    restart: unless-stopped
    
  worker:
    container_name: authentik-worker
    image: beryju/authentik:latest
    command: worker
    networks:
      - proxy
    volumes:
      - /mnt/user/appdata/authentik/backups:/backups
      - /mnt/user/appdata/authentik/media:/media
      - /mnt/user/appdata/authentik/certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/user/appdata/authentik/templates:/templates
      - /mnt/user/appdata/authentik/geoip:/geoip
    environment:
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_POSTGRESQL__HOST=postgres
      - AUTHENTIK_POSTGRESQL__USER=${POSTGRES_USER:-authentik}
      - AUTHENTIK_POSTGRESQL__NAME=${POSTGRES_DB:-authentik}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${POSTGRES_PASSWORD}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=true
      - AUTHENTIK_SECRET_KEY=${secret_key}
    restart: unless-stopped
  
networks:
  proxy:
    name: ${DOCKER_NETWORK}
    driver: bridge
    external: true
    