---
version: '3'
services:
  db_cache:
    container_name: redis_authentik
    image: bitnami/redis:latest
    networks:
      - proxy
    ports:
      - ${SERVER_NAME}:6379:6379
    volumes:
      - /mnt/user/appdata/redis_authentik/bitnami:/bitnami
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped

  db_sql:
    container_name: postgres_authentik
    image: postgres:12.5-alpine
    networks:
      - proxy
    ports:
      - ${SERVER_NAME}:5432:5432
    volumes:
      - /mnt/user/appdata/postgres_authentik/data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped

networks:
  proxy:
    name: ${DOCKER_NETWORK}
    driver: bridge
    external: true
    
