services:
  sftpgo:
    container_name: SFTPGo
    image: drakkan/sftpgo
    networks:
      - devrack
    deploy:
      resources:
        limits:
          pids: 2048
    ports:
      - ${SERVER_IP}:2221:8080/tcp
      - ${SERVER_IP}:2121:2121/tcp
      - ${SERVER_IP}:2022:2022/tcp
      - ${SERVER_IP}:50000-50100:50000-50100/tcp
      - ${SERVER_IP}:10080:10080/tcp
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - HOST_OS=Unraid
      - HOST_HOSTNAME=dev-laptop
      - HOST_CONTAINERNAME=SFTPGo
      - SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP=192.168.1.93
      - SFTPGO_COMMON__DEFENDER__ENABLED=true
      - SFTPGO_FTPD__PASSIVE_PORT_RANGE__START=0 # off
      - SFTPGO_FTPD__PASSIVE_PORT_RANGE__END=0 # off
      - SFTPGO_FTPD__BINDINGS__0__PORT=0 # off
      - SFTPGO_WEBDAVD__BINDINGS__0__PORT=10080 
      - SFTPGO_FTPD__BINDINGS__0__DEBUG=0
      # Branding
      - SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_CLIENT__NAME=Alexandria Cloud
      - SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_CLIENT__SHORT_NAME=Alexandria Cloud
      - SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_ADMIN__NAME=Alexandria Admin Cloud
      - SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_ADMIN__SHORT_NAME=Alexandria Admin Cloud
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui='http://[IP]:[PORT:2221]'
      - net.unraid.docker.icon='https://raw.githubusercontent.com/CorneliousJD/Docker-Templates/master/icons/sftpgo.png'
    volumes:
      - /mnt/user/appdata/cloud/sftpgo/data:/srv/sftpgo/data:rw
      - /mnt/user/appdata/cloud/sftpgo/backups:/srv/sftpgo/backups:rw
      - /mnt/user/appdata/cloud/sftpgo/config:/var/lib/sftpgo:rw
      - /mnt/user/cloud/:/cloud:rw

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
