services:
  arch-qbittorrentvpn:
    image: binhex/arch-qbittorrentvpn
    container_name: qbittorrentvpn
    cap_add: # adds network admin privileges
        - NET_ADMIN
    networks:
      - devrack
    ports:
        - ${SERVER_IP}:7984:7984
        - 8118:8118
        - 9118:9118
        - 58946:58946
        - 58946:58946/udp
    volumes:
        - /mnt/user/appdata/sparrow/qbittorrentvpn/data:/data
        - /mnt/user/appdata/sparrow/qbittorrentvpn/config:/config
        - /etc/localtime:/etc/localtime:ro
    environment:
        - VPN_ENABLED=yes
        - VPN_USER=${VPN_USER}
        - VPN_PASS=${VPN_PASS}
        - VPN_PROV=${VPN_PROV}
        - VPN_CLIENT=openvpn
        - ENABLE_STARTUP_SCRIPTS=no
        - ENABLE_PRIVOXY=yes
        - STRICT_PORT_FORWARD=yes
        - USERSPACE_WIREGUARD=no
        - ENABLE_SOCKS=no
        - SOCKS_USER=
        - SOCKS_PASS=
        - LAN_NETWORK=192.168.1.0/24
        - NAME_SERVERS=${NAME_SERVERS}
        - VPN_INPUT_PORTS=
        - VPN_OUTPUT_PORTS=
        - DEBUG=false
        - WEBUI_PORT=7984
        - UMASK=000
        - PUID=${PUID}
        - PGID=${PGID}
networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
