---
version: '3'
services:
  delugevpn:
    container_name: delugevpn
    image: binhex/arch-delugevpn:latest
    networks:
      - proxy
    ports:
      - ${SERVER_NAME}:<PORTS>:<PORTS>
    volumes:
      - /mnt/user/appdata/<SERVICE_NAME>/<CONTAINER>/:/
    environment:
    restart: unless-stopped
  
networks:
  proxy:
    name: ${DOCKER_NETWORK}
    driver: bridge
    external: true
    