---
version: '3'
services:
  delugevpn:
    container_name: delugevpn
    image: binhex/arch-delugevpn:latest
    networks:
      - proxy
    ports:
      - ${SERVER_NAME}:8112:8112
      - ${SERVER_NAME}:8118:8118
      - ${SERVER_NAME}:58846:58846
      - ${SERVER_NAME}:58946:58946
    volumes:
      - /mnt/user/appdata/sparrow/binhex-delugevpn:/config
      - /mnt/user/Scratch/Downloads/:/data
    environment:
      VPN_ENABLED: yes
      VPN_USER: ${VPN_USER}
      VPN_PASS: ${VPN_PASS}
      VPN_PROV: ${VPN_PROV}
      VPN_CLIENT: openvpn
      STRICT_PORT_FORWARD: 'yes'
      ENABLE_PRIVOXY: no
      LAN_NETWORK: ${LAN_NETWORK}
      NAME_SERVERS: ${NAME_SERVERS}
      DELUGE_DAEMON_LOG_LEVEL: info
      DELUGE_WEB_LOG_LEVEL: info
      DEBUG: false
    restart: unless-stopped

networks:
  proxy:
    name: ${DOCKER_NETWORK}
    driver: bridge
    external: true
