---
version: '3'
services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    runtime: nvidia
    networks:
      - devrack
    env_file:
      - ../server.env
      - ./jellyfin.env
    ports:
      - "${SERVER_IP}:8096:8096"
      - "${SERVER_IP}:8920:8920" # HTTPS
      - "${SERVER_IP}:1900:1900/udp" # Service Discovery
    volumes:
      - /mnt/user/appdata/external/jellyfin:/config
      - /mnt/user/media/:/media
      - /mnt/user/media/metadata:/metadata
    environment:
      - PUID=99
      - PGID=100
      - TZ='America/Chicago'
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_GPUID}
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui='http://[IP]:[PORT:8096]'
      - net.unraid.docker.icon='https://raw.githubusercontent.com/binhex/docker-templates/master/binhex/images/jellyfin-icon.png'
    restart: unless-stopped

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
