---
version: '3'
services:
  homeassistant:
    container_name: HomeAssistant
    image: lscr.io/linuxserver/homeassistant:latest
    networks:
      - devrack
    env_file:
      - ../server.env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui='http://[IP]:[PORT:8123]'
      - net.unraid.docker.icon='https://avatars.githubusercontent.com/u/13844975?s=200&v=4'
    ports:
      - "${SERVER_IP}:8123:8123" # Application WebUI, only use this if you are not using host mode.
    volumes:
      - /mnt/user/appdata/internal/Home_Assistant/:/config
    restart: unless-stopped

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
