---
services:
  homeassistant:
    container_name: home_assistant
    image: lscr.io/linuxserver/homeassistant:latest
    networks:
      - proxy
    env_file:
      - ../server.env
    ports:
      - "${SERVER_IP}:8123:8123" # Application WebUI, only use this if you are not using host mode.
    volumes:
      - /mnt/user/appdata/internal/Home_Assistant/:/config
    restart: unless-stopped

networks:
  proxy:
    name: ${DOCKER_NETWORK}
    driver: bridge
    external: true
