version: '3'
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file:
      - ../server.env
    networks:
      - devrack
    environment:
      - HOST_OS=Unraid
      - HOST_HOSTNAME=Alexandria
      - HOST_CONTAINERNAME=homepage
      - PORT=3000
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui='http://[IP]:[PORT:80]'
      - net.unraid.docker.icon='https://raw.githubusercontent.com/gethomepage/homepage/main/public/android-chrome-512x512.png'
    ports:
      - 3000:3000
    volumes:
      - /mnt/user/appdata/internal/homepage/:/app/config
      - /mnt/user/DevRack/DevRackConfig/Assets:/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
