---
version: '3'
services:
  unifibackup:
    container_name: Unifi_Protect_Backup
    image: ghcr.io/ep1cman/unifi-protect-backup:latest
    networks:
      - proxy
    volumes:
      - /mnt/user/appdata/internal/Unifi_Backup/:/config
      - /mnt/user/Backups/Unifi_Protect/:/data # ONLY USED WITH LOCAL RCLONE REMOTE
    environment:
      TZ: 'America/Chicago'
      UFP_USERNAME: ${UNIFI_USERNAME}
      UFP_PASSWORD: ${UNIFI_PASSWORD}
      UFP_ADDRESS: ${UNIFI_ADDRESS}
      UFP_PORT: 443
      UFP_SSL_VERIFY: 'false'
      RCLONE_RETENTION: 60d
      RCLONE_DESTINATION: 'local:/data'
      IGNORE_CAMERAS:
      VERBOSITY: v
      RCLONE_ARGS: 
    restart: unless-stopped
  
networks:
  proxy:
    name: ${DOCKER_NETWORK}
    driver: bridge
    external: true
    