---
version: '3'
services:

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    networks:
      - proxy
    env_file:
      - ../server.env
      - ./bookstack.env
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_ROOT_PASSWORD: <yourdbpass>
      TZ: 'America/Chicago'
      MYSQL_DATABASE: bookstackapp
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: <yourdbpass>
    volumes:
      - /path/to/data:/config
    restart: unless-stopped

  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    networks:
      - proxy
    env_file:
      - ../server.env
      - ./bookstack.env
    environment:
      PUID: 1000
      PGID: 1000
      APP_URL: http://${SERVER_IP}:6875
      DB_HOST: bookstack_db
      DB_PORT: 3306
      DB_USER: bookstack
      DB_PASS: <yourdbpass>
      DB_DATABASE: bookstackapp
    volumes:
      - /path/to/data:/config
    ports:
      - "${SERVER_IP}:6875:80"
    restart: unless-stopped
    depends_on:
      - bookstack_db

networks:
  proxy:
    name: ${DOCKER_NETWORK}
    driver: bridge
    external: true
