---
version: '3'
services:

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    networks:
      - devrack
    env_file:
      - ../server.env
      - ./bookstack.env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${BOOKSTACK_DB_PASSWORD}
      MYSQL_DATABASE: ${BOOKSTACK_DB_NAME}
      MYSQL_USER: ${BOOKSTACK_DB_USER}
      MYSQL_PASSWORD: ${BOOKSTACK_DB_PASSWORD}
    volumes:
      - /mnt/user/appdata/docs/bookstack_db/config:/config
    restart: unless-stopped

  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    networks:
      - devrack
    env_file:
      - ../server.env
      - ./bookstack.env
    ports:
      - "${SERVER_IP}:${BOOKSTACK_PORT}:80"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      APP_URL: http://${SERVER_IP}:${BOOKSTACK_PORT}
      DB_HOST: bookstack_db
      DB_PORT: 3306
      DB_USER: ${BOOKSTACK_DB_USER}
      DB_PASS: ${BOOKSTACK_DB_PASSWORD}
      DB_DATABASE: ${BOOKSTACK_DB_NAME}
      # email
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_ENCRYPTION: tls
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      # The "from" email address for outgoing email
      MAIL_FROM: ${MAIL_FROM}
      # The "from" name used for outgoing email
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
    volumes:
      - /mnt/user/appdata/docs/bookstack/config:/config
    restart: unless-stopped
    depends_on:
      - bookstack_db

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: True
