---
version: '3'
services:

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    networks:
      - devrack
    env_file:
      - ../server.env
      - ./bookstack.env
    environment:
      PUID: 99
      PGID: 100
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'America/Chicago'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /mnt/user/appdata/docs/bookstack_db/config:/config
    restart: unless-stopped

  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    networks:
      - proxy
    env_file:
      - ../server.env
      - ./bookstack.env
    environment:
      PUID: 99
      PGID: 100
      APP_URL: http://${SERVER_IP}:6875
      DB_HOST: bookstack_db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
      # email
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_ENCRYPTION: tls
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      # The "from" email address for outgoing email
      MAIL_FROM: ${MAIL_FROM}
      # The "from" name used for outgoing email
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
    volumes:
      - /mnt/user/appdata/docs/bookstack/config:/config
    ports:
      - "${SERVER_IP}:6875:80"
    restart: unless-stopped
    depends_on:
      - bookstack_db

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: True