version: "3"
services:

  db:
    image: postgres:11-alpine
    networks:
      - proxy
    env_file:
      - ../server.env
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    networks:
      - proxy
    env_file:
      - ../server.env
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  db-data:

networks:
  proxy:
    name: ${DOCKER_NETWORK}
    driver: bridge
    external: true
