---
version: '3'
services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    networks:
      - proxy
    env_file:
      - ../server.env
    ports:
      - "${SERVER_IP}:7878:7878" # If port differs change in /config/config.xml
    volumes:
      - /mnt/user/appdata/arrs/radarr:/config
      - /mnt/user/media:/media
      - /mnt/user/scratch/Downloads/movie:/data/downloads/movie
    environment:
      - TZ=America/Chicago
      - PUID=99
      - PGID=100
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:develop # bump to version 4
    networks:
      - proxy
    env_file:
      - ../server.env
    ports:
      - "${SERVER_IP}:8989:8989" # If port differs change in /config/config.xml
    volumes:
      - /dev/rtc:/dev/rtc:ro
      - /mnt/user/appdata/arrs/sonarr:/config
      - /mnt/user/media:/media
      - /mnt/user/scratch/Downloads/tv:/data/downloads/tv
    environment:
      - TZ=America/Chicago
      - PUID=99
      - PGID=100
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    networks:
      - proxy
    env_file:
      - ../server.env
    ports:
      - "${SERVER_IP}:9696:9696" # If port differs change in /config/config.xml
    volumes:
      - /mnt/user/appdata/arrs/prowlarr:/config
    environment:
      - TZ=America/Chicago
      - PUID=99
      - PGID=100
    restart: unless-stopped

  flaresolverr:
    container_name: flaresolverr
    image: lscr.io/linuxserver/flaresolverr:latest
    depends_on:
      - prowlarr
    networks:
      - proxy
    env_file:
      - ../server.env
    ports:
      - "${SERVER_IP}:8191:8191"
    environment:
      - TZ=America/Chicago
    restart: unless-stopped

#  jackett:
#    container_name: jackett
#    image: lscr.io/linuxserver/jackett:latest
#    networks:
#      - proxy
#    env_file:
#      - ../server.env
#    ports:
#      - "${SERVER_IP}:9117:9117" # If port differs change in /config/ServerConfig.json
#    volumes:
#      - /mnt/user/appdata/arrs/jackett:/config # Creates additional layer
#      - /mnt/user/scratch/Downloads:/downloads
#    environment:
#      - TZ=America/Chicago
#    restart: unless-stopped

  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr:latest
    networks:
      - proxy
    env_file:
      - ../server.env
    volumes:
      - /mnt/user/appdata/arrs/recyclarr:/config
    environment:
      - TZ=America/Chicago
    restart: unless-stopped

networks:
  proxy:
    name: ${DOCKER_NETWORK}
    driver: bridge
    external: true
