#
#  _______         __      ________        __      _______    _______    
# |_   __ \       /  \    |_   ___ \.     /  \    |_   __ \  |_   __ \   
#   | |__) |     / /\ \     | |   \. \   / /\ \     | |__) |   | |__) |  
#   |  __ /     / ____ \    | |    | |  / ____ \    |  __ /    |  __ /   
#  _| |  \ \_ _/ /    \ \_ _| |___.' /_/ /    \ \_ _| |  \ \_ _| |  \ \_ 
# |____| |___|____|  |____|________.'|____|  |____|____| |___|____| |___|
#

radarr:
  radarr:
    base_url: !secret radarr_url
    api_key: !secret radarr_apikey

    delete_old_custom_formats: true

    quality_definition:
      type: movie

    quality_profiles:
      - name: Standard
        reset_unmatched_scores:
          enabled: false
        score_set: Standard-1080p
        min_format_score: 0
        upgrade:
          allowed: true
          until_quality: Remux-1080p
        qualities:
          - name: Remux-2160p
            enabled: false
          - name: Bluray-2160p
            enabled: false
          - name: WEB 2160p
            enabled: false
            qualities:
              - name: WEBRip-2160p
                enabled: false
              - name: WEBDL-2160p
                enabled: false
          - name: HDTV-2160p
            enabled: false
          - name: Remux-1080p
          - name: Bluray-1080p
          - name: WEB 1080p
            qualities:
              - name: WEBRip-1080p
              - name: WEBDL-1080p
          - name: HDTV-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - name: WEBRip-720p
              - name: WEBDL-720p
          - name: HDTV-720p
          - name: Bluray-576p
          - name: Bluray-480p
          - name: WEB 480p
            qualities:
              - name: WEBDL-480p
              - name: WEBRip-480p
          - name: DVD-R
          - name: DVD
        quality_sort: top

      - name: Anime
        reset_unmatched_scores:
          enabled: false
        score_set: Anime
        min_format_score: 0
        upgrade:
          allowed: true
          until_quality: Remux-1080p
        qualities:
          - name: Remux-2160p
          - name: Bluray-2160p
          - name: WEB 2160p
            qualities:
              - name: WEBRip-2160p
              - name: WEBDL-2160p
          - name: HDTV-2160p
          - name: Remux-1080p
          - name: Bluray-1080p
          - name: WEB 1080p
            qualities:
              - name: WEBRip-1080p
              - name: WEBDL-1080p
          - name: HDTV-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - name: WEBRip-720p
              - name: WEBDL-720p
          - name: HDTV-720p
          - name: Bluray-576p
          - name: Bluray-480p
          - name: WEB 480p
            qualities:
              - name: WEBDL-480p
              - name: WEBRip-480p
          - name: DVD-R
          - name: DVD
        quality_sort: top

      - name: Ultra-HD
        reset_unmatched_scores:
          enabled: false
        score_set: Standard-4K
        min_format_score: 0
        upgrade:
          allowed: true
          until_quality: Remux-2160p
        qualities:
          - name: Remux-2160p
          - name: Bluray-2160p
          - name: WEB 2160p
            qualities:
              - name: WEBRip-2160p
              - name: WEBDL-2160p
          - name: HDTV-2160p
          - name: Remux-1080p
          - name: Bluray-1080p
          - name: WEB 1080p
            enabled: false
            qualities:
              - name: WEBRip-1080p
              - name: WEBDL-1080p
          - name: HDTV-1080p
            enabled: false
          - name: Bluray-720p
            enabled: false
          - name: WEB 720p
            enabled: false
            qualities:
              - name: WEBRip-720p
              - name: WEBDL-720p
          - name: HDTV-720p
            enabled: false
        quality_sort: top

    custom_formats:
      - trash_ids:
          - 9170d55c319f4fe40da8711ba9d8050d # https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/#x265
          quality_profiles:
            - name: Standard
            - name: Ultra-HD
            - name: Anime
            - score: 5

    # Anime Trash_IDs
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
          quality_profiles:
            - name: Anime
              score: 10 # Adjust scoring as desired

#
#   _______   ____   ____  _____      __      _______    _______    
#  /  ___  |.'    \.|_   \|_   _|    /  \    |_   __ \  |_   __ \   
# |  (__ \_|  .--.  \ |   \ | |     / /\ \     | |__) |   | |__) |  
#  '.___\-.| |    | | | |\ \| |    / ____ \    |  __ /    |  __ /   
# |\\____) |  \--'  /_| |_\   |_ _/ /    \ \_ _| |  \ \_ _| |  \ \_ 
# |_______.'\.____.'|_____|\____|____|  |____|____| |___|____| |___|
#
#

sonarr:
  sonarr:
    base_url: !secret sonarr_url
    api_key: !secret sonarr_apikey

    delete_old_custom_formats: true

    quality_definition: 
      type: series

    quality_profiles:
      - name: Ultra-HD
        reset_unmatched_scores:
          enabled: false
        score_set: Standard-4K
        min_format_score: 0
        upgrade:
          allowed: true
          until_quality: Bluray-2160p
        qualities:
          - name: Bluray-2160p Remux
          - name: Bluray-2160p
          - name: WEB 2160p
            qualities:
              - name: WEBRip-2160p
              - name: WEBDL-2160p
          - name: HDTV-2160p
          - name: Bluray-1080p Remux
          - name: Bluray-1080p
          - name: WEB 1080p
            qualities:
              - name: WEBDL-1080p
              - name: WEBRip-1080p
          - name: Bluray-720p
            enabled: false
          - name: WEB 720p
            enabled: false
            qualities:
              - name: WEBDL-720p
                enabled: false
              - name: WEBRip-720p
                enabled: false
          - name: Raw-HD
            enabled: false
          - name: HDTV-1080p
            enabled: false
          - name: HDTV-720p
            enabled: false
          - name: DVD
            enabled: false
            qualities:
              - name: Bluray-480p
            enabled: false
              - name: DVD
            enabled: false
          - name: WEB 480p
            enabled: false
            qualities:
              - name: WEBDL-480p
                enabled: false
              - name: WEBRip-480p
                enabled: false
          - name: SDTV
            enabled: false
          - name: Unknown
            enabled: false
        quality_sort: top

      - name: Standard
        reset_unmatched_scores:
          enabled: false
        score_set: Standard-1080p
        min_format_score: 0
        upgrade:
          allowed: true
          until_quality: Bluray-1080p
        qualities:
          - name: Bluray-2160p Remux
            enabled: false
          - name: Bluray-2160p
            enabled: false
          - name: WEB 2160p
            enabled: false
            qualities:
              - name: WEBRip-2160p
                enabled: false
              - name: WEBDL-2160p
                enabled: false
          - name: HDTV-2160p
            enabled: false
          - name: Bluray-1080p Remux
          - name: Bluray-1080p
          - name: WEB 1080p
            qualities:
              - name: WEBDL-1080p
              - name: WEBRip-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - name: WEBDL-720p
              - name: WEBRip-720p 
          - name: Raw-HD
            enabled: false
          - name: HDTV-1080p
          - name: HDTV-720p
          - name: DVD
            qualities:
              - name: Bluray-480p
              - name: DVD
          - name: WEB 480p
            qualities:
              - name: WEBDL-480p
              - name: WEBRip-480p
          - name: SDTV
            enabled: false
          - name: Unknown
            enabled: false
        quality_sort: top

      - name: Anime
        reset_unmatched_scores:
          enabled: false
        score_set: Anime
        min_format_score: 0
        upgrade:
          allowed: true
          until_quality: Bluray-1080p
        qualities:
          - name: Bluray-2160p Remux
            enabled: false
          - name: Bluray-2160p
            enabled: false
          - name: WEB 2160p
            enabled: false
            qualities:
              - name: WEBRip-2160p
                enabled: false
              - name: WEBDL-2160p
                enabled: false
          - name: HDTV-2160p
            enabled: false
          - name: Bluray-1080p Remux
          - name: Bluray-1080p
          - name: WEB 1080p
            qualities:
              - name: WEBDL-1080p
              - name: WEBRip-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - name: WEBDL-720p
              - name: WEBRip-720p 
          - name: Raw-HD
            enabled: false
          - name: HDTV-1080p
          - name: HDTV-720p
          - name: DVD
            qualities:
              - name: Bluray-480p
              - name: DVD
          - name: WEB 480p
            qualities:
              - name: WEBDL-480p
              - name: WEBRip-480p
          - name: SDTV
            enabled: false
          - name: Unknown
            enabled: false

    custom_formats:
      - trash_ids:
          - c9eafd50846d299b862ca9bb6ea91950 # https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/#x265
        quality_profiles:
          - name: Anime
          - name: Standard
          - name: Ultra-HD
            score: 5

    # Anime Trash_IDs
      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        quality_profiles:
          - name: Anime
            score: 10
