---
version: '3'
services:
  czkawka:
    container_name: czkawka
    image: jlesage/czkawka:latest
    networks:
      - proxy
    ports:
      - ${SERVER_NAME}:7821:5800
      - ${SERVER_NAME}:7921:5900
    volumes:
      - /mnt/user/appdata/extra/czkawka/:/config
      - /mnt/user/:/storage
    environment:
      SECURE_CONNECTION: 0
    restart: unless-stopped
  
  krusader:
    container_name: krusader
    image: jlesage/czkawka:latest
    networks:
      - proxy
    ports:
      - ${SERVER_NAME}:8080:8080
    volumes:
      - /mnt/user/appdata/extra/krusader/:/krusader
      - /mnt/user/:/mnt/user
    environment:
      USER_LOCALES: 'en_US.UTF-8 UTF-8'
      RUNASROOT: false
    restart: unless-stopped
  
networks:
  proxy:
    name: ${DOCKER_NETWORK}
    driver: bridge
    external: true
    