---
version: '3'
services:
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    networks:
      - devrack
    env_file:
      - ../server.env
    ports:
      - "${SERVER_IP}:5055:5055" # webUI port
    volumes:
      - /mnt/user/appdata/external/jellyseerr:/app/config/
    environment:
      - PUID=99
      - PGID=100
      - LOG_LEVEL='info'
      - TZ='America/Chicago'
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui='http://[IP]:[PORT:5055]'
      - net.unraid.docker.icon='https://raw.githubusercontent.com/Fallenbagel/jellyseerr/develop/public/android-chrome-512x512_maskable.png'
    restart: unless-stopped

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
