---
version: '3'
services:
  mariadb:
    container_name: nextcloud_db
    image: lscr.io/linuxserver/mariadb:latest
    networks:
      - proxy
    env_file:
      - ../server.env
      - ./cloud.env
    ports:
      - "${SERVER_IP}:3306:${MARIADB_PORT}"
    volumes:
      - /mnt/user/appdata/cloud/mariadb/config:/config
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      TZ: 'America/Chicago'
    # MYSQL_DATABASE=USER_DB_NAME #optional
    # MYSQL_USER=MYSQL_USER #optional
    # MYSQL_PASSWORD=DATABASE_PASSWORD #optional
    restart: unless-stopped

  nextcloud:
    container_name: nextcloud
    image: lscr.io/linuxserver/nextcloud:latest
    depends_on:
      - 'mariadb'
    networks:
      - proxy
    ports:
      - 444:444 # Changing port causes issues.
    volumes:
      - /mnt/user/NextCloud/:/data
      - /mnt/user/appdata/cloud/nextcloud/config:/config
      - ${NEXTCLOUD_LOCAL_MOUNT}:/data/alexandria/Adam # local Adam mount
    environment:
      TZ: 'America/Chicago'
    restart: unless-stopped

networks:
  proxy:
    name: ${DOCKER_NETWORK}
    driver: bridge
    external: true